export const backendQuestions = [
   {
      id: '1',
      questionText: 'Вопрос 1?',
      answerOptions: ['ответ 1-1', 'ответ 1-2+', 'ответ 1-3', 'ответ 1-4'],
      rightIndexesOfAnswers: [1],
      indexesOfUserAnswers: [],
      isAnswer: false,
      isAnswerRight: null as boolean | null,
   },
   {
      id: '2',
      questionText: 'Вопрос 2?',
      answerOptions: ['ответ 2-1', 'ответ 2-2', 'ответ 2-3+', 'ответ 2-4'],
      rightIndexesOfAnswers: [2],
      indexesOfUserAnswers: [],
      isAnswer: false,
      isAnswerRight: null as boolean | null,
   },
   {
      id: '3',
      questionText: 'Вопрос 3?',
      answerOptions: ['ответ 3-1', 'ответ 3-2', 'ответ 3-3', 'ответ 3-4+'],
      rightIndexesOfAnswers: [3],
      indexesOfUserAnswers: [],
      isAnswer: false,
      isAnswerRight: null as boolean | null,
   },
   {
      id: '4',
      questionText: 'Вопрос 4?',
      answerOptions: ['ответ 4-1', 'ответ 4-2', 'ответ 4-3', 'ответ 4-4+'],
      rightIndexesOfAnswers: [3],
      indexesOfUserAnswers: [],
      isAnswer: false,
      isAnswerRight: null as boolean | null,
   },
   {
      id: '5',
      questionText: 'Вопрос 5?',
      answerOptions: ['ответ 5-1+', 'ответ 5-2+', 'ответ 5-3', 'ответ 5-4'],
      rightIndexesOfAnswers: [0, 1],
      indexesOfUserAnswers: [],
      isAnswer: false,
      isAnswerRight: null as boolean | null,
   },
];
